[package]
name = "fancapripper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", features = ["blocking", "stream"] }
scraper = "0.19.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
indicatif = "0.17.8"
